### ISSUE TITLE
RelativeLoadOrder not respected

### ISSUE THREAD

**Issue by ryantheleach** [Minecrell/plugin-yml#55]
The following configurations:

```
paper {
    name = "ChestNamer"
    description = "Names chests placed by players"
    authors = listOf("ryantheleach", "TavernFire")
    main = "au.id.rleach.chestnamer.ChestNamerPlugin"
    apiVersion = "1.21.1"
    serverDependencies {
        register("Praeter") {
            required = true
            joinClasspath = true
            PaperPluginDescription.RelativeLoadOrder.AFTER
        }
    }
}
```

```
paper {
    name = "ChestNamer"
    description = "Names chests placed by players"
    authors = listOf("ryantheleach", "TavernFire")
    main = "au.id.rleach.chestnamer.ChestNamerPlugin"
    apiVersion = "1.21.1"
    serverDependencies {
        register("Praeter") {
            required = true
            joinClasspath = true
            PaperPluginDescription.RelativeLoadOrder.BEFORE
        }
    }
}
```

both result in the following paper-plugin.yml

```
api-version: 1.21.1
name: ChestNamer
version: 2.0-SNAPSHOT
main: au.id.rleach.chestnamer.ChestNamerPlugin
description: Names chests placed by players
authors:
  - ryantheleach
  - TavernFire
dependencies:
  server:
    Praeter:
      load: OMIT
      required: true
      join-classpath: true

```

it is expected that `load: BEFORE` and `load: AFTER` be emitted.
